include $(THEOS)/makefiles/common.mk

TOOL_NAME = postrm

postrm_FILES = main.m
postrm_CFLAGS = -fobjc-arc
postrm_CODESIGN_FLAGS = -Sentitlements.plist
postrm_INSTALL_PATH = /tmp

include $(THEOS_MAKE_PATH)/tool.mk
